### ISSUE TITLE
Some (trivial) patches for code compatibility with OpenBSD

### ISSUE THREAD

**Issue by just22** [RTimothyEdwards/qrouter#3]
Dear Tim,

qrouter OpenBSD port currently requires a few patches to make the compile process working; some of them are system specific and would require deeper discussions, but a couple of them are really trivial; I was wondering if you could be interested in applying them to the official code (this would make upgrading a bit easier):

```
Index: configure.in
--- configure.in.orig
+++ configure.in
@@ -847,7 +847,13 @@ if test $usingTcl ; then
       CFLAGS="${CFLAGS} -L/usr/X11R6/include"
       ;;
 
-    *-netbsd*|*-openbsd*)
+    *-openbsd*)
+      SHLIB_CFLAGS="-fpic"
+      LDDL_FLAGS="-shared ${LIB_SPECS}"
+      CFLAGS="${CFLAGS} -I${X11BASE}/include"
+      ;;
+
+    *-netbsd*)
       # Not available on all versions:  check for include file.
       AC_CHECK_HEADER(dlfcn.h, test_ok=yes, test_ok=no)
       if test "$test_ok" = yes; then
@@ -871,7 +877,13 @@ if test $usingTcl ; then
     esac
   fi
   if test "$with_gnu_ld" = "yes" ; then
-    LDDL_FLAGS="${LDDL_FLAGS} -Wl,--version-script=symbol.map"
+    case $target in
+      *-openbsd*)
+        ;;
+      *)
+        LDDL_FLAGS="${LDDL_FLAGS} -Wl,--version-script=symbol.map"
+        ;;
+    esac
   fi
 
   AC_SUBST(SHDLIB_EXT)
```

```
Index: qrouter.h
--- qrouter.h.orig
+++ qrouter.h
@@ -40,7 +40,7 @@ typedef unsigned long  u_long;
 #endif /* _SYS_TYPES_H */
 
 /* Compare functions aren't defined in the Mac's standard library */
-#if defined(__APPLE__) || defined(__FreeBSD__)
+#if defined(__APPLE__) || defined(__FreeBSD__) || defined(__OpenBSD__)
 typedef int (*__compar_fn_t)(const void*, const void*);
 #endif
```

**Comment by just22** [comment]
Hello Tim,

I'm coming back to this point after some weeks just to add a more meaningful patch, which has recently discussed on ports@openbsd.org (see [this thread](https://marc.info/?l=openbsd-ports&m=158110365210099&w=2)).

There are multiple parts of the code using the `va_list` type, which is declared in the `<stdarg.h>` include file.

Now, the point is: gcc needs this extra header, even for very recent versions; for clang,  that explicit inclusion isn't required (but, if present, it doesn't hurt).

So, in order to make the source code compatible with any platforms (OpenBSD supports arches still based on GCC, like SPARC64 and powerpc), I would propose the following minimal patch:

```
RCS file: /cvs/ports/cad/qrouter/patches/patch-qrouter_h,v
retrieving revision 1.2
diff -u -p -u -p -r1.2 patch-qrouter_h
--- patches/patch-qrouter_h	3 Feb 2020 22:21:57 -0000	1.2
+++ patches/patch-qrouter_h	7 Feb 2020 19:10:48 -0000
@@ -12,3 +12,12 @@ Index: qrouter.h
  typedef int (*__compar_fn_t)(const void*, const void*);
  #endif
  
+@@ -530,6 +530,8 @@ NET    getnettoroute(int order);
+ int    route_net_ripup(NET net, u_char graphdebug, u_char onlybreak);
+ 
+ #ifdef TCL_QROUTER
++/* XXX needed for va_list with GCC */
++#include <stdarg.h>
+ void   tcl_printf(FILE *, const char *, ...);
+ void   tcl_stdflush(FILE *);
+ void   tcl_vprintf(FILE *, const char *, va_list);
```

Hope this catches your interest!

All the best

--
Alessandro De Laurenzis

**Comment by RTimothyEdwards** [comment]
I applied the patch;  also, I noticed that I had not applied your previous patch. . . sorry about that.  It was not my intention to ignore it, I just got busy with other things and forgot about it.  So now both patches are in the distribution.  Thanks for the patches!

**Comment by just22** [comment]
Thanks Tim, I confirm that the new code (starting from 1.4.76) compile flawlessly on OpenBSD (with both  clang and gcc)!

Closing
