### ISSUE TITLE
write_def implicit definition 

### ISSUE THREAD

**Issue by sangramkate** [RTimothyEdwards/qrouter#5]
I took a very recent clone of this repository to install qrouter. While installing, when I hit the make command I ended up getting the implicit declaration error for `write_def()` function in main. I could bypass the error by putting a function declaration in qrouter.h header file.  After I solved this issue, I could install qrouter without any issue although I see generous warnings. 

I was installing qrouter on a Mac OS(Big Sur, 11.2).

Please fix the error if you find the same outcome.

**Comment by RTimothyEdwards** [comment]
Yes, that's needed.  Thanks for pointing it out.  I just updated the opencircuitdesign.com repository, and the github repo will update overnight.
