### ISSUE TITLE
Spacing Violations w/ Rectangular Vias

### ISSUE THREAD

**Issue by kwgilpin2020** [RTimothyEdwards/qrouter#9]
Hi, I'm using QFlow to synthesize/place/route a ~1000 gate design for a well-known commercial 180nm node.  The standard cells (provided the foundry's recommend vendor) have their pins located on a 0.28um grid.  The standard via has a square 0.26um cut sandwiched between metals that are both 0.38x0.28um.  The long axes of the two metal layers can be aligned or orthogonal.  Minimum metal width/spacing is 0.28mm.

Here's a representative *.lef section:

LAYER MET2
   TYPE ROUTING;
   DIRECTION VERTICAL;
   PITCH 0.56;
   OFFSET 0.28 ;
   WIDTH 0.28 ;
   SPACING 0.280 ;
END MET2

The problem I'm encountering is that qrouter does not appear take into account that the vias, if their long metal axis is oriented along the direction of the corresponding trace, effectively extend the length of the metal traces.  Consequently, my design has numerous DRC spacing errors.  Here's an example:

![qrouter Error](https://github.com/RTimothyEdwards/qrouter/assets/82177566/8005bc0d-a7f4-49a0-9a5e-343ac70f6ed9)

The highlighted area is overlapped MET2 / MET3.  The via is constructed such MET2 extends vertically past the end of the trace creating a spacing DRC with the horizontal jog with the trace above.  If the via were to be rotated 90deg, the DRC would just move to the west side of the via.

Is there a way to qrouter handle this type of via?

One approach I have tried is changing the vendor-provided *.lef file to define the default via metal as a 0.38mm square.  But, this necessitates changing the routing grid to 0.38mm.  Subsequently, qrouter has trouble connecting to the standard cell pins (because they fall on a 0.28mm grid).  

Thanks so much for your assistance!

**Comment by RTimothyEdwards** [comment]
Qrouter *does* handle these kind of vias and knows how to rotate them to avoid DRC errors.  However, it might have something to do with the syntax describing the via;  there are some via rule definitions that qrouter might not recognize.  Specifically, in the output DEF file, you should see a VIAS section that either has pre-defined contacts from the technology LEF in all orientations, or else defines contacts with names containing "hv", "vh", "vv", and "hh", describing the orientation of the top and bottom metal extensions.

**Comment by kwgilpin2020** [comment]
Thanks for the guidance.  Here's a representative snippet of what the LEF techfile looks like:

```
VIA VIA23_X DEFAULT
   LAYER MET2 ;
      RECT -0.19 -0.14 0.19 0.14 ;
   LAYER VIA23 ;
      RECT -0.13 -0.13 0.13 0.13 ;
   LAYER MET3 ;
      RECT -0.14 -0.19 0.14 0.19 ;
END VIA23_X

VIA VIA23_XR90 DEFAULT
   LAYER MET2 ;
      RECT -0.14 -0.19 0.14 0.19 ;
   LAYER VIA23 ;
      RECT -0.13 -0.13 0.13 0.13 ;
   LAYER MET3 ;
      RECT -0.19 -0.14 0.19 0.14 ;
END VIA23_XR90

VIA VIA23_LH DEFAULT
   LAYER MET2 ;
      RECT -0.19 -0.14 0.19 0.14 ;
   LAYER VIA23 ;
      RECT -0.13 -0.13 0.13 0.13 ;
   LAYER MET3 ;
      RECT -0.19 -0.14 0.19 0.14 ;
END VIA23_LH

VIA VIA23_LV DEFAULT
   LAYER MET2 ;
      RECT -0.14 -0.19 0.14 0.19 ;
   LAYER VIA23 ;
      RECT -0.13 -0.13 0.13 0.13 ;
   LAYER MET3 ;
      RECT -0.14 -0.19 0.14 0.19 ;
END VIA23_LV


VIARULE VGEN23 GENERATE
   LAYER MET2 ;
      ENCLOSURE 0.01 0.06 ;
   LAYER MET3 ;
      ENCLOSURE 0.06 0.01 ;
   LAYER VIA23 ;
      RECT -0.13 -0.13 0.13 0.13 ;
      SPACING 0.52 BY 0.52 ;
END VGEN23
```

And the output DEF from qrouter:

```
VIAS 15 ;
...
- VGEN23_3
+ RECT VIA23 ( -26 -26 ) ( 26 26 )
+ RECT MET2 ( -28 -38 ) ( 28 38 )
+ RECT MET3 ( -28 -38 ) ( 28 38 ) ;
- VGEN23_2
+ RECT VIA23 ( -26 -26 ) ( 26 26 )
+ RECT MET2 ( -38 -28 ) ( 38 28 )
+ RECT MET3 ( -38 -28 ) ( 38 28 ) ;
- VGEN23_1
+ RECT VIA23 ( -26 -26 ) ( 26 26 )
+ RECT MET2 ( -38 -28 ) ( 38 28 )
+ RECT MET3 ( -28 -38 ) ( 28 38 ) ;
- VGEN23_0
+ RECT VIA23 ( -26 -26 ) ( 26 26 )
+ RECT MET3 ( -38 -28 ) ( 38 28 )
+ RECT MET2 ( -28 -38 ) ( 28 38 ) ;
...
- VGEN23_0_post
+ RECT MET2 ( -818 -38 ) ( 818 38 )
+ RECT VIA23 ( 754 -26 ) ( 806 26 )
+ RECT VIA23 ( 598 -26 ) ( 650 26 )
+ RECT VIA23 ( 442 -26 ) ( 494 26 )
+ RECT VIA23 ( 286 -26 ) ( 338 26 )
+ RECT VIA23 ( 130 -26 ) ( 182 26 )
+ RECT VIA23 ( -26 -26 ) ( 26 26 )
+ RECT VIA23 ( -182 -26 ) ( -130 26 )
+ RECT VIA23 ( -338 -26 ) ( -286 26 )
+ RECT VIA23 ( -494 -26 ) ( -442 26 )
+ RECT VIA23 ( -650 -26 ) ( -598 26 )
+ RECT VIA23 ( -806 -26 ) ( -754 26 )
+ RECT MET3 ( -818 -38 ) ( 818 38 ) ;
...
END VIAS
```

Do these snippets look as expected?  Is there something I should change in the LEF to make qrouter behave appropriately?

Thanks,
Kyle

**Comment by RTimothyEdwards** [comment]
@kwgilpin2020 :  Yes, that output looks right.  Qrouter ignored the various via definitions and used the "generate" definition to create four different vias with different metal orientations (which have _0, _1, _2, and _3 extensions, not _hv, _vh, etc., as I claimed above---memory glitch on my part).  So I'm not entirely sure why it ended up with a DRC error and did not rotate the via;  it might be a bug in qrouter.  I know that the check for which via orientation to output is in the code, but it looks like it is not being exercised in some cases.

Just to check one thing:  Is more than one of those via definitions (VGEN23_0 to VGEN23_3) being used in the NETS section?

**Comment by RTimothyEdwards** [comment]
"If the via were to be rotated 90deg, the DRC would just move to the west side of the via."

Sorry, I somehow missed or failed to read that statement correctly.  So qrouter is not really designed to solve difficult routing problems, and expects that all the routing parameters are defined such that vias can be placed cleanly (in some orientation) at a track intersection without causing a DRC error.  It will not reroute to avoid such errors;  it assumes that there is always a DRC-clean solution and then just looks for the via orientation that creates the clean solution.  If the track pitches have been defined such that a via simply cannot be placed at a track intersection without causing a DRC error in one direction or the other, then qrouter will not be able to find a solution that does not cause a DRC violation.

Unfortunately, foundries now use standard cell designs that simply assume that they will be routed with a commercial router and that they should just compress everything to the minimum possible size and spacing and let the router figure it out.  Qrouter works well with loosely-constrained standard cell sets like the OSU standard cells.  When pitches get very tight, it will fail.  If you don't have a standard cell set that is not, in effect, "high density", then you should probably switch to OpenROAD, which is as close to a commercial-grade router as you can get in open source EDA tools.

**Comment by RTimothyEdwards** [comment]
That said, though, I *have* used qrouter with not too-terribly constrained standard cell sets and been able to generate layout for design sizes of around a few thousand gates with qrouter producing few enough DRC errors (several hundred, say) that I could fix them all by hand.  That is obviously not the preferred solution, but it worked for me a few times before OpenROAD became available.

**Comment by kwgilpin2020** [comment]
Thanks for all the good feedback!  qrouter is an awesome tool, and an amazing resource.  I'll check out OpenROAD for this design, and if that fails, I can splurge and buy a short-term license for one of the commercial tools.
